# Generated by Django 6.0.6 on 2026-06-18 09:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailotp',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
