# Generated by Django 6.0.6 on 2026-06-04 04:11

import apps.listings.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('property_type', models.CharField(choices=[('single_room', 'Single Room'), ('two_rooms', '2 Rooms'), ('flat', 'Flat'), ('apartment', 'Apartment'), ('house', 'House'), ('hostel', 'Hostel'), ('office', 'Office Space'), ('shutter', 'Shutter')], max_length=30)),
                ('city', models.CharField(max_length=100)),
                ('area', models.CharField(max_length=200)),
                ('ward_number', models.PositiveIntegerField(blank=True, null=True)),
                ('exact_address', models.CharField(blank=True, max_length=255)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('monthly_rent', models.PositiveIntegerField()),
                ('security_deposit', models.PositiveIntegerField(default=0)),
                ('bills_water_included', models.BooleanField(default=False)),
                ('bills_electricity_included', models.BooleanField(default=False)),
                ('bills_internet_included', models.BooleanField(default=False)),
                ('furnished_status', models.CharField(choices=[('furnished', 'Furnished'), ('unfurnished', 'Unfurnished'), ('semi_furnished', 'Semi-Furnished')], default='unfurnished', max_length=30)),
                ('available_date', models.DateField(blank=True, null=True)),
                ('rules', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('rejection_reason', models.TextField(blank=True)),
                ('is_owner_verified', models.BooleanField(default=False)),
                ('is_property_verified', models.BooleanField(default=False)),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='listings', to='locations.district')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to=settings.AUTH_USER_MODEL)),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='listings', to='locations.province')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ListingDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('citizenship_front', models.ImageField(upload_to=apps.listings.models.listing_document_upload_path)),
                ('citizenship_back', models.ImageField(upload_to=apps.listings.models.listing_document_upload_path)),
                ('lalpurja', models.ImageField(upload_to=apps.listings.models.listing_document_upload_path)),
                ('selfie_with_citizenship', models.ImageField(upload_to=apps.listings.models.listing_document_upload_path)),
                ('verification_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('extracted_name', models.CharField(blank=True, max_length=255)),
                ('extracted_citizenship_number', models.CharField(blank=True, max_length=100)),
                ('extracted_address', models.CharField(blank=True, max_length=255)),
                ('admin_notes', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('listing', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='listings.listing')),
            ],
        ),
        migrations.CreateModel(
            name='ListingFacility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_parking', models.BooleanField(default=False)),
                ('bike_parking', models.BooleanField(default=False)),
                ('wifi', models.BooleanField(default=False)),
                ('drinking_water', models.BooleanField(default=False)),
                ('water_24_7', models.BooleanField(default=False)),
                ('attached_bathroom', models.BooleanField(default=False)),
                ('balcony', models.BooleanField(default=False)),
                ('furnished', models.BooleanField(default=False)),
                ('cctv', models.BooleanField(default=False)),
                ('security_guard', models.BooleanField(default=False)),
                ('pet_allowed', models.BooleanField(default=False)),
                ('laundry', models.BooleanField(default=False)),
                ('kitchen', models.BooleanField(default=False)),
                ('listing', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='facilities', to='listings.listing')),
            ],
        ),
        migrations.CreateModel(
            name='ListingImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=apps.listings.models.listing_image_upload_path)),
                ('is_primary', models.BooleanField(default=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='listings.listing')),
            ],
            options={
                'ordering': ['-is_primary', 'uploaded_at'],
            },
        ),
    ]
