# Generated by Django 6.0.6 on 2026-06-11 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0002_advertisement'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='advertisements/videos/'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='advertisements/'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='position',
            field=models.CharField(choices=[('home_top', 'Homepage Top Banner'), ('home_between_cards', 'Homepage Between Cards'), ('detail_below_images', 'Listing Detail Below Images'), ('detail_sidebar', 'Listing Detail Sidebar'), ('phone_reveal_video', 'Phone Reveal Video Ad')], max_length=50),
        ),
    ]
